### PR TITLE
UDP functionality addedd

### PR DESCRIPTION
**Pull request by steveww**
Added support for UDP sendto and recvfrom.
Added support for getting firmware version from the board.
Added the F() macro to some strings to reduce memory footprint.
Possibly some other stuff I forgot about.

### CODE REVIEW

**Comment by Sweet-Peas** [comment]
@steveww , @wadetb Would it be interesting to combine our efforts in tinyhci ? If so I'd like to add some review comments to this commit. I'm working on a way to detect CC3000 deadlocks so the system will never lock up and it would be great if we could have tinyhci as a stable alternative to TI's pile of junk.
/Pontus

**Comment by wadetb** [comment]
Thanks for the PR @steveww, this looks like great stuff.  @Sweet-Peas I'd definitely like to combine efforts.

**Comment by wadetb** [comment]
@steveww I'd like to revert the whitespace changes in this PR - they make it harder to identify the actual functional changes, and will make the code history harder to understand.  

We don't have a formal code style per se, which means the rule is to just follow what's there.  
Also, I'd like to see the code comment updated to list what's actually changed, per http://365git.tumblr.com/post/3308646748/writing-git-commit-messages.

I'd be happy to take your commit, amend and submit it (with credit to you in the code comment) if you'd prefer!

Thanks,
Wade

**Comment by steveww** [comment]
I am happy to work with you guys and contribute what I can. However I have a very busy day job so the hours I can put in to this will be limited and sporadic. If you want to tidy up the code and commit it yourself go ahead. 

I tweaked some of the white space to make it easier for me to read, I guess I am used to the way I lay things out.

One feature I would like to work on is SPI friendliness. My Arduino project has 2 SPI devices with slightly different requirements. I need to investigate way to make them play nice with each other. I agree making the CC3000 driver code more robust is also a very good idea. The trick will be doing this and keeping it small. So far I have not found any way to analyse what is using the space in the code.

**Comment by Sweet-Peas** [comment]
@steveww , Sounds great. I have just added a few simple comments but I agree with Wade that the white space changes should be in a separate commit to keep things easier to follow. @wadetb I can have a look at Steve's changes and align them with my upcoming merge and do everything in one sweep if you want to ?

**Comment by wadetb** [comment]
@Sweet-Peas I think I'd prefer to see @steveww's change submitted before your changes.  It's quite orthogonal and ideally each commit is a minimal forward step which maintains or increases functionality.  I'll take care of the submit shortly.

Best,
Wade

**Comment by wadetb** [comment]
OK, it's committed.  Thanks @steveww!

Regarding analyzing code size, I build Arduino projects on my MacBook Air using the Ino (inotool.org) framework and this Makefile:

```
OBJDUMP=/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-objdump

all:
    ino build -m micro
    $(OBJDUMP) -d -S -j .text .build/micro/firmware.elf > firmware.s
```

Then I can open firmware.s and compare addresses of functions to calculate sizes.

**Pull request closed without merging**
